apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${{ values.project_name }}
  namespace: openshift-gitops
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Project to hold the different Argo applications

  # Allow manifests to deploy from specific Git repos
  sourceRepos:
  - '*'

  # Limit the namespaces to which the project can deploy
  destinations:
  - server: https://kubernetes.default.svc
    namespace: '*'
#  - server: https://api.celeron.demolab.local:6443
#    namespace: '*'

  # Deny all cluster-scoped resources from being created, except for named items
  clusterResourceWhitelist:
  - group: ${{ values.project_name }}-dev
    kind: Namespace
  - group: ${{ values.project_name }}-build
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding

  # Allow all namespaced-scoped resources to be created except named items
  namespaceResourceBlacklist:

  # Deny all namespaced-scoped resources from being created, except for named items
  namespaceResourceWhitelist:

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  roles:
  # A role which provides read-only access to all applications in the project

  # A role which provides sync privileges to only the guestbook-dev application, e.g. to provide
  # sync privileges to a CI system