apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${{ values.project_name }}
  namespace: openshift-gitops
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Project to hold the different Argo applications

  # Allow manifests to deploy from specific Git repos
  sourceRepos:
  - '*'

  sourceNamespaces:
  - '*'

  # Limit the namespaces to which the project can deploy
  destinations:
  - server: https://kubernetes.default.svc
    namespace: '*'

  # Deny all cluster-scoped resources from being created, except for named items
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"

  # Deny all namespaced-scoped resources from being created, except for named items
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false