apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ${{values.component_id}}-argocd-project.yaml
- role-bindings/argocd-admin.yaml
- rest-heroes/${{values.component_id}}-rest-heroes-argocd-app-dev-build.yaml
- rest-heroes/${{values.component_id}}-rest-heroes-argocd-app-dev.yaml
#- rest-fights/${{values.component_id}}-rest-fights-argocd-app-dev-build.yaml
#- rest-fights/${{values.component_id}}-rest-fights-argocd-app-dev.yaml
- monitoring/${{values.component_id}}-monitoring-argocd-app-dev.yaml
- rest-heroes/namespace-build.yaml
- rest-heroes/namespace-dev.yaml
